
# Binance API Keys (con permessi di lettura per Futures)
[binance]
api_key = "IDmaD14ykyeEglSRAXOayxYKEkjZlymzk5RNtTe7VOzhOIeEm9Kn8BoB03eH33lU"
api_secret = "8yC5kbWPpQ0qyR4dKNmku9GNZyym33JDjyrRVCi6T2ySj3FRn4UuyQq4N6KgW1ZS"


[finnhub]
api_key = "d3fpv1hr01qolknebeq0d3fpv1hr01qolknebeqg"

[bybit]
api_key = "NIGDfhz8OkvPXqprDO"
api_secret = "OGznGdUnYMdj23G0A1jMlGyXbpOnaAANLbyz"